--- #YAML:1.0
name:               Sphinx-Config-Builder
version:            1.02
abstract:           ~
author:  []
license:            perl
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker: 0 
build_requires:
    Test::More:  0.98
requires:  {}
resources:
    bugtracker:   http://rt.cpan.org/Public/Dist/Display.html?Name=Sphinx-Config-Builder
    web:          https://github.com/estrabd/perl-Sphinx-Config-Builder
    repository:   git://github.com/estrabd/perl-Sphinx-Config-Builder.git
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.57_05
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
dynamic_config:     0
