---
abstract: 'Perl extension dynamically creating Sphinx configuration files  on the fly, using a backend datasource to drive the indexes, sources, and their relationships.'
author:
  - 'B. Estrade <estrabd@gmail.com>'
build_requires:
  ExtUtils::MakeMaker: '0'
configure_requires:
  ExtUtils::MakeMaker: '0'
dynamic_config: 0
generated_by: 'ExtUtils::MakeMaker version 6.98, CPAN::Meta::Converter version 2.141520'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Sphinx-Config-Builder
no_index:
  directory:
    - t
    - inc
requires:
  Test::More: '0.99'
resources:
  repository: git://github.com/estrabd/perl-Sphinx-Config-Builder.git
version: '1.02'
